# Generated by Django 3.2.3 on 2021-05-31 20:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.IntegerField(blank=True, default=16, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='DDD')),
                ('numero', models.CharField(blank=True, help_text='Exemplo de entrada 00000-0000', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='O formato do campo está inválido', regex='[0-9]{4,5}-[0-9]{4}')])),
                ('tipo', models.CharField(choices=[('Cel', 'Celular'), ('Res', 'Residencial'), ('Com', 'Comercial')], default='Cel', max_length=11, null=True)),
            ],
            options={
                'unique_together': {('ddd', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('rg', models.CharField(help_text='O campo RG tem que ser do tipo 00.000.000-00', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='O formato do campo está inválido', regex='[0-9]{2,3}\\.[0-9]{3}\\.[0-9]{3}-[0-9]{1,2}')], verbose_name='RG')),
                ('cpf', models.CharField(help_text='O campo CPF tem que ser do tipo 000.000.000-00', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='O formato do campo está inválido', regex='[0-9]{2,3}\\.[0-9]{3}\\.[0-9]{3}-[0-9]{1,2}')], verbose_name='CPF')),
                ('data_nasc', models.CharField(help_text='Entre com a data de nascimento (e.g. dd/mm/yyyy)', max_length=10, validators=[django.core.validators.RegexValidator(message='O formato do campo está inválido', regex='[0-9]{2}/[0-9]{2}/[0-9]{4}')], verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(max_length=12)),
                ('campo_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='banco_dados.email')),
                ('telefone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='banco_dados.telefone')),
            ],
        ),
    ]
